---
- name: Install k3s on target hosts
  become: true
  hosts: all
  # vars_files:
  #   - ../../group_vars/values.yaml
  tasks:
    - name: Add helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.key }}"
        repo_url: "{{ item.value }}"
      with_dict:
        ingress-nginx: https://kubernetes.github.io/ingress-nginx
    - name: Install required kubernetes library
      ansible.builtin.pip:
        name: kubernetes
    - name: "Create ingress-nginx namespace"
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: "ingress-nginx"
        api_version: v1
        kind: Namespace
        state: present

